apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: kwt-development
spec:
  replicas: 2
  selector:
    matchLabels:
      project: kwt
      app: front
      env: development
  template:
    metadata:
      labels:
        project: kwt
        app: front
        env: development
    spec:
      containers:
        - name: front
          image: wondookong/kwt-development-front:latest
          ports:
            - containerPort: 3000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64